# Role IDs
ROLE_SUPER_ADMIN = 1
ROLE_ADMIN = 2
ROLE_COLLABORATOR = 3
ROLE_FULL_VIEWER = 4
ROLE_RESTRICTED_VIEWER = 5

# Claim IDs
CLAIM_GET_GROUP = 1
CLAIM_EDIT_GROUP = 2
CLAIM_LEAVE_GROUP = 3
CLAIM_DELETE_GROUP = 4
CLAIM_TRANSFER_OWNERSHIP = 5
CLAIM_ACTIVATE_DEACTIVATE_GROUP = 6
CLAIM_ADD_MEMBER = 7
CLAIM_REMOVE_MEMBER = 8
CLAIM_VIEW_ALL_MEMBERS = 9
CLAIM_UPDATE_MEMBER_ROLE = 10
CLAIM_VIEW_YOUR_PHOTOS = 11
CLAIM_VIEW_ALL_PHOTOS = 12
CLAIM_UPLOAD_PHOTOS = 13
CLAIM_DELETE_PHOTOS = 14


 


# Backblaze B2 Configuration
BACKBLAZE_ACCESS_KEY = '0066745095b4eb50000000001'
BACKBLAZE_SECRET_KEY = 'K006d2ySktCZGM+L/HfRcTMCp2BJWHw'
BACKBLAZE_ENDPOINT = 'https://s3.ca-east-006.backblazeb2.com'
BACKBLAZE_BUCKET_NAME = 'SnapVault-Storage'


# File Size Limit for profile picture
MAX_FILE_SIZE_BYTES_PROFILE_PICTURE = 20 * 1024 * 1024


# Highlighting Constants
HIGHLIGHT_THRESHOLD = 3.0
SIMILARITY_THRESHOLD = 0.6 
