# Role IDs
ROLE_SUPER_ADMIN = 1
ROLE_ADMIN = 2
ROLE_COLLABORATOR = 3
ROLE_FULL_VIEWER = 4
ROLE_RESTRICTED_VIEWER = 5

# Claim IDs
CLAIM_GET_GROUP = 1
CLAIM_EDIT_GROUP = 2
CLAIM_LEAVE_GROUP = 3
CLAIM_DELETE_GROUP = 4
CLAIM_TRANSFER_OWNERSHIP = 5
CLAIM_ACTIVATE_DEACTIVATE_GROUP = 6
CLAIM_ADD_MEMBER = 7
CLAIM_REMOVE_MEMBER = 8
CLAIM_VIEW_ALL_MEMBERS = 9
CLAIM_UPDATE_MEMBER_ROLE = 10
CLAIM_VIEW_YOUR_PHOTOS = 11
CLAIM_VIEW_ALL_PHOTOS = 12
CLAIM_UPLOAD_PHOTOS = 13
CLAIM_DELETE_PHOTOS = 14


#other constants
UPLOAD_PROFILE_DIR = "uploads/profile_pictures" 
THRESHOLD = 0.6
UPLOAD_DIR = "uploads/photos"
